M48
; DRILL file {KiCad (6.0.2)} date Mon Apr 25 16:55:12 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-25T16:55:12-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X4.2736Y-1.8001
X4.2736Y-5.0166
X7.4114Y-1.8001
X7.4114Y-5.0166
T0
M30
