M48
; DRILL file {KiCad (6.0.1)} date Mon Mar 21 02:35:54 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-21T02:35:54-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X4.2789Y-1.8201
X4.2789Y-5.0366
X7.4167Y-1.8201
X7.4167Y-5.0366
T0
M30
